//------------------------------------------------------------------------------
// <auto-generated>
// This class was auto generated by the AI Name Map Generator
// </auto-generated>
//------------------------------------------------------------------------------
namespace Apex.AI
{
    using System;

    public static class AINameMap
    {
		public static readonly Guid fgsgf = new Guid("7264eb13-582a-4c08-bf12-8894f5e58a6f");

    }
}
